version: 1
formatters:
  simple:
    format: "%(asctime)s.%(msecs)d [%(levelname)s] [%(userdata)s] [%(filename)s:%(lineno)d]: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
      class: utils.safe_rotating_file_handler.SafeRotatingFileHandler
      level: DEBUG
      formatter: simple
      filename: logs/app_execution.log
      encoding: utf-8
      maxBytes: 1048576
      backupCount: 3
loggers:
  bragerNotifier:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  requests:
    level: DEBUG
    handlers: [file]
root:
  level: DEBUG
  handlers: [console]